config/routes.rb
Rails.application.routes.draw do
  get 'welcome/show'

  root 'welcome#show'
  resources :property_staffs
  resources :customer_staffs
  resources :appointment_staffs
  resources :properties
  resources :appointments
  resources :staffs
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer_staff.rb
class CustomerStaff < ApplicationRecord
	belongs_to :customer 
	belongs_to :staff 
end

app/controllers/customer_staffs_controller.rb
class CustomerStaffsController < ApplicationController
  before_action :set_customer_staff, only: [:show, :edit, :update, :destroy]

  # GET /customer_staffs
  # GET /customer_staffs.json
  def index
    @customer_staffs = CustomerStaff.all
  end

  # GET /customer_staffs/1
  # GET /customer_staffs/1.json
  def show
  end

  # GET /customer_staffs/new
  def new
    @customer_staff = CustomerStaff.new
  end

  # GET /customer_staffs/1/edit
  def edit
  end

  # POST /customer_staffs
  # POST /customer_staffs.json
  def create
    @customer_staff = CustomerStaff.new(customer_staff_params)

    respond_to do |format|
      if @customer_staff.save
        format.html { redirect_to @customer_staff, notice: 'Customer staff was successfully created.' }
        format.json { render :show, status: :created, location: @customer_staff }
      else
        format.html { render :new }
        format.json { render json: @customer_staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_staffs/1
  # PATCH/PUT /customer_staffs/1.json
  def update
    respond_to do |format|
      if @customer_staff.update(customer_staff_params)
        format.html { redirect_to @customer_staff, notice: 'Customer staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_staff }
      else
        format.html { render :edit }
        format.json { render json: @customer_staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_staffs/1
  # DELETE /customer_staffs/1.json
  def destroy
    @customer_staff.destroy
    respond_to do |format|
      format.html { redirect_to customer_staffs_url, notice: 'Customer staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_staff
      @customer_staff = CustomerStaff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_staff_params
      params.fetch(:customer_staff, {})
    end
end

app/helpers/customer_staffs_helper.rb
module CustomerStaffsHelper
end

app/views/customer_staffs/_form.html.erb
<%= form_with(model: customer_staff, local: true) do |form| %>
  <% if customer_staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_staff.errors.count, "error") %> prohibited this customer_staff from being saved:</h2>

      <ul>
      <% customer_staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customer_staffs/edit.html.erb
<h1>Editing Customer Staff</h1>

<%= render 'form', customer_staff: @customer_staff %>

<%= link_to 'Show', @customer_staff %> |
<%= link_to 'Back', customer_staffs_path %>

app/views/customer_staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Staffs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_staffs.each do |customer_staff| %>
      <tr>
        <td><%= link_to 'Show', customer_staff %></td>
        <td><%= link_to 'Edit', edit_customer_staff_path(customer_staff) %></td>
        <td><%= link_to 'Destroy', customer_staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer Staff', new_customer_staff_path %>

app/views/customer_staffs/new.html.erb
<h1>New Customer Staff</h1>

<%= render 'form', customer_staff: @customer_staff %>

<%= link_to 'Back', customer_staffs_path %>

app/views/customer_staffs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_customer_staff_path(@customer_staff) %> |
<%= link_to 'Back', customer_staffs_path %>