config/routes.rb
Rails.application.routes.draw do
  get 'welcome/show'

  root 'welcome#show'
  resources :property_staffs
  resources :customer_staffs
  resources :appointment_staffs
  resources :properties
  resources :appointments
  resources :staffs
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment_staff.rb
class AppointmentStaff < ApplicationRecord
	belongs_to :staff 
	belongs_to :appointments 
end

app/controllers/appointment_staffs_controller.rb
class AppointmentStaffsController < ApplicationController
  before_action :set_appointment_staff, only: [:show, :edit, :update, :destroy]

  # GET /appointment_staffs
  # GET /appointment_staffs.json
  def index
    @appointment_staffs = AppointmentStaff.all
  end

  # GET /appointment_staffs/1
  # GET /appointment_staffs/1.json
  def show
  end

  # GET /appointment_staffs/new
  def new
    @appointment_staff = AppointmentStaff.new
  end

  # GET /appointment_staffs/1/edit
  def edit
  end

  # POST /appointment_staffs
  # POST /appointment_staffs.json
  def create
    @appointment_staff = AppointmentStaff.new(appointment_staff_params)

    respond_to do |format|
      if @appointment_staff.save
        format.html { redirect_to @appointment_staff, notice: 'Appointment staff was successfully created.' }
        format.json { render :show, status: :created, location: @appointment_staff }
      else
        format.html { render :new }
        format.json { render json: @appointment_staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointment_staffs/1
  # PATCH/PUT /appointment_staffs/1.json
  def update
    respond_to do |format|
      if @appointment_staff.update(appointment_staff_params)
        format.html { redirect_to @appointment_staff, notice: 'Appointment staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment_staff }
      else
        format.html { render :edit }
        format.json { render json: @appointment_staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_staffs/1
  # DELETE /appointment_staffs/1.json
  def destroy
    @appointment_staff.destroy
    respond_to do |format|
      format.html { redirect_to appointment_staffs_url, notice: 'Appointment staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment_staff
      @appointment_staff = AppointmentStaff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_staff_params
      params.fetch(:appointment_staff, {})
    end
end

app/helpers/appointment_staffs_helper.rb
module AppointmentStaffsHelper
end

app/views/appointment_staffs/_form.html.erb
<%= form_with(model: appointment_staff, local: true) do |form| %>
  <% if appointment_staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment_staff.errors.count, "error") %> prohibited this appointment_staff from being saved:</h2>

      <ul>
      <% appointment_staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointment_staffs/edit.html.erb
<h1>Editing Appointment Staff</h1>

<%= render 'form', appointment_staff: @appointment_staff %>

<%= link_to 'Show', @appointment_staff %> |
<%= link_to 'Back', appointment_staffs_path %>

app/views/appointment_staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointment Staffs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointment_staffs.each do |appointment_staff| %>
      <tr>
        <td><%= link_to 'Show', appointment_staff %></td>
        <td><%= link_to 'Edit', edit_appointment_staff_path(appointment_staff) %></td>
        <td><%= link_to 'Destroy', appointment_staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment Staff', new_appointment_staff_path %>

app/views/appointment_staffs/new.html.erb
<h1>New Appointment Staff</h1>

<%= render 'form', appointment_staff: @appointment_staff %>

<%= link_to 'Back', appointment_staffs_path %>

app/views/appointment_staffs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_appointment_staff_path(@appointment_staff) %> |
<%= link_to 'Back', appointment_staffs_path %>